//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JayBookerBackEnd.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccomodationRates
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AccomodationRates()
        {
            this.SupplierRates = new HashSet<SupplierRates>();
        }
    
        public int AccomodationRateID { get; set; }
        public string AccomodationRateName { get; set; }
        public decimal AccomodationSingle { get; set; }
        public decimal AccomodationDouble { get; set; }
        public decimal AccomodationTriple { get; set; }
        public decimal AccomodationQuad { get; set; }
        public System.DateTime AccomodationRateStartDate { get; set; }
        public System.DateTime AccomodationRateEndDate { get; set; }
        public bool AccomodationRateIsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SupplierRates> SupplierRates { get; set; }
    }
}
