//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JayBookerBackEnd.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accomodations
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Accomodations()
        {
            this.Bookings = new HashSet<Bookings>();
        }
    
        public int AccomodationID { get; set; }
        public int FK_AccomodationTypeID { get; set; }
        public string AccomodationName { get; set; }
        public string AccomodationDescription { get; set; }
        public byte AccomodationMaxOccupancy { get; set; }
        public bool AccomodationIsPublic { get; set; }
        public byte AccomodationPriority { get; set; }
        public decimal AccomodationExtraCharge { get; set; }
        public bool AccomodationIsActive { get; set; }
    
        public virtual AccomodationTypes AccomodationTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bookings> Bookings { get; set; }
    }
}
