//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JayBookerBackEnd.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bookings
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bookings()
        {
            this.BookingHistory = new HashSet<BookingHistory>();
            this.Emails = new HashSet<Emails>();
            this.InvoicedBookings = new HashSet<InvoicedBookings>();
        }
    
        public int BookingID { get; set; }
        public int FK_UserID { get; set; }
        public int FK_GuestID { get; set; }
        public Nullable<int> FK_DepartureID { get; set; }
        public Nullable<int> FK_AccomodationID { get; set; }
        public System.DateTime BookingDate { get; set; }
        public System.DateTime BookingCreatedOn { get; set; }
        public string BookingVoucher { get; set; }
        public string BookingStatus { get; set; }
        public short BookingAdultsCount { get; set; }
        public short BookingFreeAdultsCount { get; set; }
        public short BookingChildrenCount { get; set; }
        public short BookingFreeChildrenCount { get; set; }
        public short BookingStudentsCount { get; set; }
        public bool BookingModified { get; set; }
        public bool BookingIsActive { get; set; }
    
        public virtual Accomodations Accomodations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookingHistory> BookingHistory { get; set; }
        public virtual Departures Departures { get; set; }
        public virtual Guests Guests { get; set; }
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Emails> Emails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoicedBookings> InvoicedBookings { get; set; }
    }
}
