//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JayBookerBackEnd.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookingHistory
    {
        public int BookingHistoryID { get; set; }
        public int FK_UserID { get; set; }
        public int FK_BookingID { get; set; }
        public System.DateTime BookingHistoryCreatedOn { get; set; }
        public string BookingHistoryAction { get; set; }
    
        public virtual Bookings Bookings { get; set; }
        public virtual Users Users { get; set; }
    }
}
