//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JayBookerBackEnd.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Departures
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Departures()
        {
            this.Bookings = new HashSet<Bookings>();
            this.Logbook = new HashSet<Logbook>();
        }
    
        public int DepartureID { get; set; }
        public Nullable<int> FK_SeasonID { get; set; }
        public Nullable<int> FK_ShipID { get; set; }
        public string DepartureHour { get; set; }
        public System.DateTime DepartureDate { get; set; }
        public short DepartureMaxPassengers { get; set; }
        public Nullable<short> DepartureMaxAdults { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bookings> Bookings { get; set; }
        public virtual Seasons Seasons { get; set; }
        public virtual Ships Ships { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Logbook> Logbook { get; set; }
    }
}
