//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JayBookerBackEnd.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emails
    {
        public int EmailID { get; set; }
        public int FK_UserID { get; set; }
        public Nullable<int> FK_GuestID { get; set; }
        public Nullable<int> FK_BookingID { get; set; }
        public int FK_EmailTemplateID { get; set; }
        public string EmailText { get; set; }
        public string EmailSubject { get; set; }
        public bool EmailSent { get; set; }
        public Nullable<System.DateTime> EmailSentOn { get; set; }
        public string EmailTo { get; set; }
        public string EmailFrom { get; set; }
    
        public virtual Bookings Bookings { get; set; }
        public virtual Guests Guests { get; set; }
        public virtual Users Users { get; set; }
        public virtual EmailTemplates EmailTemplates { get; set; }
    }
}
