//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JayBookerBackEnd.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Guests
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Guests()
        {
            this.Bookings = new HashSet<Bookings>();
            this.Emails = new HashSet<Emails>();
            this.Invoices = new HashSet<Invoices>();
        }
    
        public int GuestID { get; set; }
        public int FK_SupplierID { get; set; }
        public string GuestFirstName { get; set; }
        public string GuestLastName { get; set; }
        public string GuestPhone { get; set; }
        public string GuestEmail { get; set; }
        public string GuestAddress { get; set; }
        public string GuestCity { get; set; }
        public string GuestCountry { get; set; }
        public string GuestPostalCode { get; set; }
        public string GuestDescription { get; set; }
        public string GuestUserName { get; set; }
        public string GuestPasswordHash { get; set; }
        public string GuestCreditCardHash { get; set; }
        public string GuestCCExpiry { get; set; }
        public string GuestCVVHash { get; set; }
        public string GuestLanguage { get; set; }
        public bool GuestOptIn { get; set; }
        public System.DateTime GuestCreatedOn { get; set; }
        public bool GuestIsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bookings> Bookings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Emails> Emails { get; set; }
        public virtual Suppliers Suppliers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Invoices> Invoices { get; set; }
    }
}
