//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JayBookerBackEnd.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoicedBookings
    {
        public int FK_InvoiceID { get; set; }
        public int FK_BookingID { get; set; }
        public Nullable<decimal> InvoicedAdultPrice { get; set; }
        public Nullable<decimal> InvoicedFreeAdultPrice { get; set; }
        public Nullable<decimal> InvoicedChildrenPrice { get; set; }
        public Nullable<decimal> InvoicedFreeChildrenPrice { get; set; }
        public Nullable<decimal> InvoicedStudentPrice { get; set; }
        public Nullable<decimal> InvoicedAccomodationPrice { get; set; }
    
        public virtual Bookings Bookings { get; set; }
    }
}
