//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JayBookerBackEnd.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoicedProducts
    {
        public int FK_InvoiceID { get; set; }
        public int FK_ProductID { get; set; }
        public Nullable<decimal> InvoicedQuantity { get; set; }
    
        public virtual Invoices Invoices { get; set; }
        public virtual Products Products { get; set; }
    }
}
