//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JayBookerBackEnd.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoices
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Invoices()
        {
            this.Payments = new HashSet<Payments>();
        }
    
        public int InvoiceID { get; set; }
        public int FK_UserID { get; set; }
        public int FK_GuestID { get; set; }
        public System.DateTime InvoiceDate { get; set; }
        public string InvoiceStatus { get; set; }
        public decimal InvoiceDiscount { get; set; }
        public string InvoiceDiscountReason { get; set; }
    
        public virtual Guests Guests { get; set; }
        public virtual InvoicedProducts InvoicedProducts { get; set; }
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payments> Payments { get; set; }
    }
}
