//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JayBookerBackEnd.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payments
    {
        public int PaymentID { get; set; }
        public int FK_InvoiceID { get; set; }
        public string PaymentMethod { get; set; }
        public string PaymentTransactionNumber { get; set; }
        public System.DateTime PaymentDate { get; set; }
    
        public virtual Invoices Invoices { get; set; }
    }
}
