//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JayBookerBackEnd.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShipRates
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ShipRates()
        {
            this.SupplierRates = new HashSet<SupplierRates>();
        }
    
        public int ShipRateID { get; set; }
        public string ShipRateName { get; set; }
        public decimal ShipRateAdult { get; set; }
        public decimal ShipRateFreeAdult { get; set; }
        public decimal ShipRateChildren { get; set; }
        public decimal ShipRateFreeChildren { get; set; }
        public decimal ShipRateStudent { get; set; }
        public System.DateTime ShipRateStartDate { get; set; }
        public System.DateTime ShipRateEndDate { get; set; }
        public bool ShipRateIsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SupplierRates> SupplierRates { get; set; }
    }
}
