//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JayBookerBackEnd.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ships
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ships()
        {
            this.Departures = new HashSet<Departures>();
        }
    
        public int ShipID { get; set; }
        public int FK_ShipDesignID { get; set; }
        public string ShipName { get; set; }
        public string ShipDescription { get; set; }
        public byte ShipMaxPassengers { get; set; }
        public bool ShipIsPublic { get; set; }
        public byte ShipPriority { get; set; }
        public bool ShipIsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Departures> Departures { get; set; }
        public virtual ShipDesigns ShipDesigns { get; set; }
    }
}
