//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JayBookerBackEnd.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplierRates
    {
        public int FK_SupplierID { get; set; }
        public int FK_ShipRateID { get; set; }
        public int FK_AccomodationRateID { get; set; }
        public string SupplierRateName { get; set; }
        public bool SuplierRateIsActive { get; set; }
    
        public virtual AccomodationRates AccomodationRates { get; set; }
        public virtual ShipRates ShipRates { get; set; }
        public virtual Suppliers Suppliers { get; set; }
    }
}
