//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JayBookerBackEnd.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Suppliers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Suppliers()
        {
            this.Guests = new HashSet<Guests>();
        }
    
        public int SupplierID { get; set; }
        public string CompanyName { get; set; }
        public string SupplierContactFirstName { get; set; }
        public string SupplierContactLastName { get; set; }
        public string SupplierContactPhone { get; set; }
        public string SupplierSecondaryPhone { get; set; }
        public string SupplierExtension { get; set; }
        public string SupplierEmail { get; set; }
        public string SupplierAddress { get; set; }
        public string SupplierCity { get; set; }
        public string SupplierCountry { get; set; }
        public string SupplierPostalCode { get; set; }
        public string SupplierDescription { get; set; }
        public bool SupplierIsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Guests> Guests { get; set; }
        public virtual SupplierRates SupplierRates { get; set; }
    }
}
